FROM golang:1.22-alpine AS builder
WORKDIR /app
RUN apk add --no-cache git
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o bin/worker ./cmd/worker

FROM alpine:3.20
RUN apk add --no-cache ca-certificates tzdata chromium
WORKDIR /app
COPY --from=builder /app/bin/worker .
COPY --from=builder /app/templates ./templates
ENV CHROME_PATH=/usr/bin/chromium-browser
CMD ["./worker"]
