apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blueprint-roi-ingress
  namespace: blueprint-roi
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - roi-api.blueprintautomation.tech
    secretName: blueprint-roi-api-tls
  rules:
  - host: roi-api.blueprintautomation.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blueprint-roi-api
            port:
              number: 8093
