CREATE TABLE questions (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    key             TEXT NOT NULL,
    category        TEXT NOT NULL DEFAULT 'general',
    question        TEXT NOT NULL,
    hint            TEXT,
    input_type      TEXT NOT NULL DEFAULT 'hours_slider',
    options         JSONB NOT NULL DEFAULT '[]',
    min_value       NUMERIC,
    max_value       NUMERIC,
    default_value   NUMERIC,
    unit            TEXT NOT NULL DEFAULT 'hours/week',
    hours_per_unit  NUMERIC NOT NULL DEFAULT 1.0,
    is_automatic    BOOLEAN NOT NULL DEFAULT false,
    automation_pct  NUMERIC(4,3) NOT NULL DEFAULT 0.75,
    relevant_products JSONB NOT NULL DEFAULT '[]',
    sort_order      INTEGER NOT NULL DEFAULT 0,
    is_active       BOOLEAN NOT NULL DEFAULT true,
    is_required     BOOLEAN NOT NULL DEFAULT false,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (tenant_id, key)
);

CREATE TABLE products (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id           UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    key                 TEXT NOT NULL,
    name                TEXT NOT NULL,
    description         TEXT NOT NULL,
    category            TEXT NOT NULL DEFAULT 'automation',
    setup_fee           NUMERIC(10,2),
    monthly_fee         NUMERIC(10,2),
    roi_description     TEXT,
    min_weekly_hours    NUMERIC NOT NULL DEFAULT 2.0,
    relevant_keys       JSONB NOT NULL DEFAULT '[]',
    required_answers    JSONB NOT NULL DEFAULT '{}',
    est_hours_saved_pw  NUMERIC NOT NULL DEFAULT 5.0,
    time_to_roi_months  INTEGER NOT NULL DEFAULT 3,
    sort_order          INTEGER NOT NULL DEFAULT 0,
    is_active           BOOLEAN NOT NULL DEFAULT true,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (tenant_id, key)
);
